services:
  db:
    image: postgres:15-alpine
    container_name: leasewise-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lozinka
      POSTGRES_DB: leasewise
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
